name: 'ASim-ToArm'
description: 'This GitHub Action converts the ASIM Parser in the Microsoft GitHub format to deployable ARM templates'
branding:
  icon: 'check-square'
  color: 'green'
inputs:
  filesPath:
    description:  'path to the existing files'
    required: false
    default: ''
  outputFolder:
    description:  'Output folder for the created artifacts'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/action.ps1 `
              -filesPath '${{ inputs.filesPath }}' `
              -outputFolder '${{ inputs.outputFolder }}'
      shell: pwsh
